services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - "8443:8443"
      depends_on:
        - frontend
        - backend
      restart: always
      networks:
        - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
    container_name: frontend
    env_file:
      - .env
    volumes:
      - public_avatars_data:/app/public/avatars
    depends_on:
      - backend
    networks:
      - mynetwork


  redis:
      build: ./redis
      container_name: redis
      restart: always
      env_file:
        - .env
      volumes:
        - redis_data:/data
      networks:
        - mynetwork


volumes:
  db_data:
  redis_data:
  public_avatars_data:

networks:
  mynetwork:
    external: true