services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "3307:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - db_data:/var/lib/postgresql/15/main
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local

networks:
  mynetwork:
    external: true

