FROM node:24-bookworm-slim



WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install

COPY . .
RUN npx prisma generate
RUN npm run build

EXPOSE 8000
CMD ["sh", "-c", "npx prisma db push && npm run start:prod"]



