global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'gmail-notifications' # Matches the receiver name below

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: 'zakariamounji44499@gmail.com'       # Where you want to receive notifications
    from: 'zakariamounji44499@gmail.com'         # Your sending Gmail address
    smarthost: 'smtp.gmail.com:587'           # Official Google SMTP outbound server
    auth_username: 'zakariamounji44499@gmail.com'
    auth_identity: 'zakariamounji44499@gmail.com'
    auth_password: 'nfrtcjamxchykdkz' # Paste token here  nfrt cjam xchy kdkz
    send_resolved: true                        # Sends a follow-up email when the service turns green again


